### ISSUE TITLE
Got an impossible result.

### ISSUE THREAD

**Issue by Haplo164** [kidfearless/Foundry-TrueRNG#10]
![roll_0_on_d6](https://user-images.githubusercontent.com/1272337/125390427-7ee56980-e368-11eb-990f-61d4aa5c6377.jpg)
Not sure where the appropriate log would be but I didn't see anything in the 2 logs I could find.

**Comment by RyamosThomas** [comment]
It appears to be a bug with how foundry rounds dice rolls and might need to be reported to the foundry guys for them to fix in the base dice roller as well. What happened was a perfect 0.0 was returned from the random number generator. Since flat 0's and flat 1's are rare this probably hasn't happened much. I'll add a check for it, but it should really be addressed by foundry and not me.
