### ISSUE TITLE
Local Pregenerated File Archive support

### ISSUE THREAD

**Issue by apoapostolov** [kidfearless/Foundry-TrueRNG#4]
Probably low priority as a free account is perfectly serviceable, but still very future-proof. 

Random Org provides daily pregenerated random data at https://archive.random.org/

Possibly, this data can be used to generate months if not years of RP random rolls with a single download, rather than rely on the API and risk the service not responding for some reason (site down, etc.) It would be great if we could use local random data instead of the Random.org service.

**Comment by RyamosThomas** [comment]
This can be added sometime in the future. Probably will pull in the historic data with the initial load of random numbers.

**Comment by RyamosThomas** [comment]
After lookin into it more, it appears that the Pregenerated File Archive format is intended for random integers not random floating point numbers. The data I'd receive could be any floating point number including invalid numbers. Scaling the integers down from int.MinValue -> int.MaxValue to 0.0 -> 1.0 could potentially cause some issues.

Due to that issue this feature won't be added.
